apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  labels:
    app: python-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: fast-app
          image: ahmadalsajid/fast-app:latest
          volumeMounts:
            - name: env-vars
              mountPath: /etc/config
      volumes:
        - name: env-vars
          configMap:
            name: config-map-demo
